### ISSUE TITLE
backward slash for relative paths in htmltestlogger resource files not working while accessing over network.

### ISSUE THREAD

**Issue by dinebhar** [Microsoft/ProtocolTestFramework#23]
Hello,

Following are the three locations where the backward slashes are used.
1.
https://github.com/Microsoft/ProtocolTestFramework/blob/master/src/htmltestlogger/Resources/functions.js#L79

    function ClickChange(caseDiv, casename)
    {
        // Change src dynamically
        document.getElementById("testcase").src = 'Html\\' + casename + '.html';
        document.getElementById('back_to_summary').style.display = '';        
       ...

2.
https://github.com/Microsoft/ProtocolTestFramework/blob/master/src/htmltestlogger/Resources/index.html#L137
        <script type="text/javascript" src="js\functions.js"></script>

3. 
https://github.com/Microsoft/ProtocolTestFramework/blob/master/src/htmltestlogger/Resources/testcase.html#L74
        <script type="text/javascript" src="..\js\functions.js"></script>

I could see the index page empty with the following error in the Firebug network analyzer.
![screenshot](https://user-images.githubusercontent.com/13114128/30636521-54a0340a-9e13-11e7-8f9d-066f06e2c45b.PNG)

I have tried replacing backward slash with forward slash and it worked
like: <script type="text/javascript" src="./js/functions.js"></script>

**Comment by JiajunW** [comment]
Hi there,

Thanks for reporting. It would be great if you can send a pull request since you have already fixed this issue :)

If you need detail information for contributing, please refer to [CONTRIBUTING.md](https://github.com/Microsoft/ProtocolTestFramework/blob/master/CONTRIBUTING.md).

**Comment by dinebhar** [comment]
hey, i think i figured out the real issue here.

i could see the issue on the older firefox browser only (I was using version 44.0.2). After updating the browser version to the latest, it worked.

i am not sure whether i should still add my fix to it or just let it discard

**Comment by JiajunW** [comment]
Yes, modern browsers are becoming smarter on compatibility. Therefore we haven't noticed that issue.

But I still think it is a good idea to use slash rather than back-slash. Your contribution is always welcomed. 😄

**Comment by JiajunW** [comment]
Fix through #24
