### ISSUE TITLE
Make XtfGetErrorText public

### ISSUE THREAD

**Issue by marsh0** [Microsoft/ProtocolTestFramework#25]
Microsoft.Internal.GamesTest.Xbox.NativeMethods.XtfGetErrorText is a very useful function to get more information about the errors you get using this framework. Could it be made public instead of internal? Otherwise we have to call the native dll ourselves.

**Comment by JiajunW** [comment]
This method seems to be a part of Xbox SDK. There is nothing to do with this project.

**Comment by JiajunW** [comment]
If you are trying to get the string representation of HRESULT, there should be other ways to achieve it. (For example, use [Win32Exception](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.win32exception?view=netframework-4.7.1))
