### ISSUE TITLE
A typo in PrerequisitesConfig.xml

### ISSUE THREAD

**Issue by guoqiao** [Microsoft/ProtocolTestFramework#27]
On this line:

https://github.com/Microsoft/ProtocolTestFramework/blob/2b36faaa2e324cf9556d7db5369e5fa3640cf38a/InstallPrerequisites/PrerequisitesConfig.xml#L3

At the end:
```
 arguments="/q /">
```
should be:
```
 arguments="/q"/>
```
This typo make the xml invalid and InstallPrerequsites.ps1 failed with following error:
```
Cannot convert value "System.Object[]" to type "System.Xml.XmlDocument". 
Error: "The 'tool' start tag on line 3 position 4 does not match the end tag 
of 'tools'. Line 6, position 4."
At C:\ProtocolTestFramework\ProtocolTestFramework-master\InstallPrerequisites\I
nstallPrerequisites.ps1:114 char:5
+     [xml]$toolXML = Get-Content -Path $DpConfigPath 
#".\PrerequisitesConfig.xml"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastToXmlDocument

```

**Comment by HsuanyaTsai** [comment]
Hi quoxiao,

The files related to InstallPrerequisites are updated.
Feel free to let us know if you have any question.
Thanks.

Regards,
MIchael

**Comment by guoqiao** [comment]
@HsuanyaTsai  Thank you for the quick response.
With the fix and the new commit today, the InstallPrerequisites.ps1 script is still not working for me.
Please refer to #28
